name: tarumt_event_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.4
  crypto: ^3.0.3
  url_launcher: ^6.3.1
  intl: ^0.20.2
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  mailer: ^6.0.1

  cupertino_icons: ^1.0.8
  file_picker: ^9.0.1
  image_picker: ^1.1.2
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  google_maps_flutter_web: ^0.5.10+1
  google_maps_flutter_platform_interface: ^2.11.1
  latlong2: ^0.8.1

  provider: 
  awesome_notifications: ^0.10.1
  firebase_messaging: ^15.2.5
  flutter_rating_bar: ^4.0.1
  googleapis: ^13.1.0
  google_sign_in: ^6.3.0
  googleapis_auth: ^1.4.1
  flutter_local_notifications: ^18.0.1
  google_maps_directions: ^0.0.3+4
  video_player: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
 
  