// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN28CcTSrdvFjBlWq0_npL-qKYwLCvJRY',
    appId: '1:1045321846037:web:1e8c1838d1583ceb39ed1c',
    messagingSenderId: '1045321846037',
    projectId: 'tarumt-event-management-app',
    authDomain: 'tarumt-event-management-app.firebaseapp.com',
    storageBucket: 'tarumt-event-management-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdGNhBjNO_QXQ_ZcOlmIbjthBGktmAE6U',
    appId: '1:1045321846037:android:22e695e92dea64b039ed1c',
    messagingSenderId: '1045321846037',
    projectId: 'tarumt-event-management-app',
    storageBucket: 'tarumt-event-management-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtUWzWxOoyo-DP344fahdWmp6Fjky3R10',
    appId: '1:1045321846037:ios:ba9a2863fac94fc439ed1c',
    messagingSenderId: '1045321846037',
    projectId: 'tarumt-event-management-app',
    storageBucket: 'tarumt-event-management-app.firebasestorage.app',
    iosBundleId: 'com.example.tarumtEventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtUWzWxOoyo-DP344fahdWmp6Fjky3R10',
    appId: '1:1045321846037:ios:ba9a2863fac94fc439ed1c',
    messagingSenderId: '1045321846037',
    projectId: 'tarumt-event-management-app',
    storageBucket: 'tarumt-event-management-app.firebasestorage.app',
    iosBundleId: 'com.example.tarumtEventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN28CcTSrdvFjBlWq0_npL-qKYwLCvJRY',
    appId: '1:1045321846037:web:eb081f78c617cfb839ed1c',
    messagingSenderId: '1045321846037',
    projectId: 'tarumt-event-management-app',
    authDomain: 'tarumt-event-management-app.firebaseapp.com',
    storageBucket: 'tarumt-event-management-app.firebasestorage.app',
  );
}
